apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"argo.cntk/instance":"openshift-pipelines"},"name":"openshift-pipelines-operator-rh","namespace":"openshift-operators"},"spec":{"channel":"stable","installPlanApproval":"Automatic","name":"openshift-pipelines-operator-rh","source":"redhat-operators","sourceNamespace":"openshift-marketplace"}}
  creationTimestamp: "2023-06-30T08:22:48Z"
  generation: 2
  labels:
    argo.cntk/instance: openshift-pipelines
    operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ""
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
  resourceVersion: "72575077"
  uid: 9b970f23-7848-4ed0-b357-fb1cfcacc09d
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-pipelines-operator-rh.v1.10.4
status:
  catalogHealth:
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: certified-operators
      namespace: openshift-marketplace
      resourceVersion: "72570516"
      uid: f355e757-54e6-4b25-a5f4-1b608c95b658
    healthy: true
    lastUpdated: "2023-08-08T03:06:57Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: community-operators
      namespace: openshift-marketplace
      resourceVersion: "72570513"
      uid: 79ba59a1-423c-4cbc-bdca-b6afa5bd29d3
    healthy: true
    lastUpdated: "2023-08-08T03:06:57Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: ibm-operator-catalog
      namespace: openshift-marketplace
      resourceVersion: "72570556"
      uid: 32030f7a-9317-4e56-92a6-971f8ef68e43
    healthy: true
    lastUpdated: "2023-08-08T03:06:57Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: redhat-marketplace
      namespace: openshift-marketplace
      resourceVersion: "72570544"
      uid: 56892d12-1327-4166-967d-3763db4c9430
    healthy: true
    lastUpdated: "2023-08-08T03:06:57Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: redhat-operators
      namespace: openshift-marketplace
      resourceVersion: "72570546"
      uid: dd736f4a-098f-4045-b63f-836e943ee34a
    healthy: true
    lastUpdated: "2023-08-08T03:06:57Z"
  conditions:
  - lastTransitionTime: "2023-08-08T03:06:57Z"
    message: all available catalogsources are healthy
    reason: AllCatalogSourcesHealthy
    status: "False"
    type: CatalogSourcesUnhealthy
  - lastTransitionTime: "2023-07-13T03:55:09Z"
    reason: ReferencedInstallPlanNotFound
    status: "True"
    type: InstallPlanMissing
  - message: 'constraints not satisfiable: no operators found in channel stable of
      package openshift-pipelines-operator-rh in the catalog referenced by subscription
      openshift-pipelines-operator-rh, subscription openshift-pipelines-operator-rh
      exists'
    reason: ConstraintsNotSatisfiable
    status: "True"
    type: ResolutionFailed
  currentCSV: openshift-pipelines-operator-rh.v1.10.4
  installPlanGeneration: 18
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-llwcx
    namespace: openshift-operators
    resourceVersion: "30026299"
    uid: 128fce20-f7ea-40b6-a4a7-a3bbd580f43d
  installedCSV: openshift-pipelines-operator-rh.v1.10.4
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-llwcx
    uuid: 128fce20-f7ea-40b6-a4a7-a3bbd580f43d
  lastUpdated: "2023-08-08T03:13:26Z"
  state: AtLatestKnown
